enable-magisk-update = true


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Video ads' 'SponsorBlock' 'Remove background playback restrictions' 'Check watch history domain name resolution' 'Remove tracking query parameter' 'Force original audio' 'Remember video quality'"
exclusive-patches = true
patcher-args = "-e 'Change header' -Oheader='premium*header' "
