enable-magisk-update = false


[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Video ads' 'SponsorBlock' 'Remove background playback restrictions' 'Check watch history domain name resolution' 'Remove tracking query parameter' 'Force original audio' 'Remember video quality'"
exclusive-patches = true
patcher-args = "-e 'Change header' -Oheader='premium*header' "

[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
build-mode = "module"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
build-mode = "module"
